name: youtube_downloader
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.1

  # youtube extractor to get audio url of youtube video
  youtube_extractor: ^1.0.3

  # youtube api to get data of youtube video

  # disable, unused
  youtube_api: ^0.7.2
  
  
  # youtube_api_v3: ^0.0.3

  # official youtube player flutter plugin
  youtube_player_flutter: ^7.0.0+7

  # flutter downloader
  # flutter_downloader: ^1.4.4

  # path provider
  # path_provider: ^1.6.11
  downloads_path_provider: ^0.1.0

  
  # permission handler
  permission_handler: ^5.0.1+1
  
  # youtube_explode_dart instead of youtube extractor 
  # download youtube audio and video
  youtube_explode_dart: ^1.4.1+3


  # editing metadata of file
  dart_tags: ^0.2.3
  # alternative to dart_tags
  audiotagger: ^1.1.0
  # or mp3editor
  mp3editor: ^0.0.2

  # beautiful drawer of the sidebar
  kf_drawer: ^1.1.2
  # needs also class_builder
  class_builder: ^1.0.1


  # Admob integraton
  # firebase_admob: ^0.9.3+2


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  # cupertino_icons: ^0.1.3

  # for adobe xd export
  # adobe_xd: ^0.1.4


  # to convert from .webm to .mp3
  flutter_ffmpeg: ^0.2.10



dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  assets:
    - images/
    - images/2.0x/
    - images/3.0x/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  fonts:
    - family: SF Pro Custom
      fonts:
        - asset: fonts/SF-Pro-Rounded-Regular.ttf

